[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/wpp"
  to   = "/wpp/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"